---
# - src: git@github.ccta.dk:devops/ansible-role-pulsar.git
#   scm: git
  - src: git@github.com:ChristianOelsner/ansible-role-docker-ce.git
    scm: git
  - src: git@github.com:ChristianOelsner/ansible-role-java.git
    scm: git
  - src: git@github.com:ChristianOelsner/ansible-role-rabbitmq.git
    scm: git
